---
- name: Automate Deployment and Database Backup
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Copy built JAR into web container
      shell: docker cp /mnt/c/Jenkins-agent/workspace/FinalSpringboot/build/libs/demo-0.0.1-SNAPSHOT.jar web:/app/build/libs/demo-0.0.1-SNAPSHOT.jar

    - name: Restart web container to apply new JAR
      shell: docker restart web

    - name: Backup the MySQL database to host
      shell: docker exec db bash -c "mysqldump -u root -pHello@123 A-PHE_Rithika-db" > D:/DevOps/FinalExam/demo/backup.sql
      no_log: true
